import type { AppConfig } from "./types"

export const defaultConfig: AppConfig = {
  theme: {
    appName: "FanC",
    primary: "#ff2e97",
    secondary: "#a855f7",
    accent: "#22d3ee",
    roomBackground: "#141a3a",
  },
  banners: [
    {
      id: "b1",
      title: "مكافآت الشحن",
      image: "/banner-rewards.png",
      gradient: "from-amber-500 via-orange-500 to-yellow-400",
    },
    {
      id: "b2",
      title: "حفلة الأبطال",
      image: "/banner-party.png",
      gradient: "from-fuchsia-600 via-purple-600 to-indigo-600",
    },
  ],
  countries: [
    { code: "EGY", name: "مصر", flag: "🇪🇬" },
    { code: "ARE", name: "الإمارات", flag: "🇦🇪" },
    { code: "QAT", name: "قطر", flag: "🇶🇦" },
    { code: "YEM", name: "اليمن", flag: "🇾🇪" },
    { code: "SAU", name: "السعودية", flag: "🇸🇦" },
  ],
  liveRooms: [
    {
      id: "r1",
      title: "ترحب بكم جميعاً",
      host: "ملكة الليل",
      cover: "/room-1.png",
      country: "مصر",
      countryFlag: "🇪🇬",
      viewers: 1536,
      tag: "دردشة",
      hot: true,
    },
    {
      id: "r2",
      title: "وليّها لد",
      host: "الوليّ",
      cover: "/room-2.png",
      country: "مصر",
      countryFlag: "🇪🇬",
      viewers: 1358,
      tag: "غناء",
      hot: true,
    },
    {
      id: "r3",
      title: "سهرة ومزاج",
      host: "نجمة",
      cover: "/room-3.png",
      country: "مصر",
      countryFlag: "🇪🇬",
      viewers: 940,
      tag: "ترفيه",
    },
    {
      id: "r4",
      title: "وكالة الأبطال",
      host: "الكابتن",
      cover: "/room-4.png",
      country: "مصر",
      countryFlag: "🇪🇬",
      viewers: 712,
      tag: "ألعاب",
    },
  ],
  roles: [
    { id: "owner", name: "مالك الغرفة", color: "#f59e0b", permissions: ["إدارة كاملة", "طرد", "كتم", "تعيين مشرفين", "قفل المايك"] },
    { id: "admin", name: "مشرف", color: "#ef4444", permissions: ["طرد", "كتم", "إدارة المقاعد"] },
    { id: "host", name: "مضيف", color: "#a855f7", permissions: ["الجلوس على المايك", "استقبال الهدايا"] },
    { id: "vip", name: "عضو VIP", color: "#22d3ee", permissions: ["دخول مميز", "تأثيرات خاصة"] },
    { id: "member", name: "عضو", color: "#94a3b8", permissions: ["الدردشة", "إرسال الهدايا"] },
  ],
  rechargePackages: [
    { id: "p1", coins: 100, bonus: 0, priceUSD: 1 },
    { id: "p2", coins: 550, bonus: 50, priceUSD: 5, popular: true },
    { id: "p3", coins: 1200, bonus: 200, priceUSD: 10 },
    { id: "p4", coins: 6500, bonus: 1500, priceUSD: 50 },
    { id: "p5", coins: 14000, bonus: 4000, priceUSD: 100 },
  ],
  agencies: [
    { id: "a1", name: "وكالة النجوم", logo: "⭐", members: 128, hosts: 42, monthlyTarget: 50000, earnings: 38200, status: "active" },
    { id: "a2", name: "وكالة الأبطال", logo: "🛡️", members: 76, hosts: 25, monthlyTarget: 30000, earnings: 21500, status: "active" },
    { id: "a3", name: "وكالة القمر", logo: "🌙", members: 34, hosts: 12, monthlyTarget: 15000, earnings: 4300, status: "pending" },
  ],
  vipLevels: [
    { level: 1, name: "VIP فضي", color: "#94a3b8", priceUSD: 5, perks: ["شارة VIP", "دخول مميز"] },
    { level: 2, name: "VIP ذهبي", color: "#f59e0b", priceUSD: 15, perks: ["إطار ذهبي", "رسائل ملونة", "إخفاء الزيارة"] },
    { level: 3, name: "VIP ماسي", color: "#22d3ee", priceUSD: 50, perks: ["تأثير دخول فاخر", "لقب حصري", "أولوية المايك"] },
  ],
  profileMenu: [
    { id: "level", label: "المستوى", icon: "gem", enabled: true },
    { id: "store", label: "المتجر", icon: "store", enabled: true },
    { id: "specialId", label: "خاص ID", icon: "badge", enabled: true },
    { id: "reward", label: "مكافأة", icon: "gift", enabled: true },
    { id: "tribe", label: "القبيلة", icon: "castle", enabled: true },
    { id: "bag", label: "حقيبة السلعة", icon: "backpack", enabled: true },
    { id: "cp", label: "CP", icon: "heart", enabled: true },
    { id: "agency", label: "انضم إلى الوكالة", icon: "shield", enabled: true },
    { id: "medal", label: "ميدالية", icon: "medal", enabled: true },
    { id: "title", label: "عنوان", icon: "crown", enabled: true },
    { id: "invite", label: "دعوة", icon: "userPlus", enabled: true },
  ],
  wallet: { coins: 200, diamonds: 0 },
  moderation: {
    enabled: true,
    message:
      "مرحبًا بك في FanC! تحذير: المواد الإباحية والابتذال والعنف والقاصرين وغيرها من المواقف ذات الصلة محظورة تمامًا أثناء البث المباشر. سيقوم نظام الذكاء الاصطناعي بالتحقق على مدار 24 ساعة في اليوم، وسيتم معاقبة أي انتهاكات بشدة!",
  },
}
