-- Pharaoh Party server-driven visual studio + admin operations
-- Applied to Supabase project fdvgpdfesvigtvmzjhnt.
alter table public.profiles add column if not exists is_admin boolean not null default false;
create table if not exists public.admin_users (user_id uuid primary key references auth.users(id) on delete cascade, created_at timestamptz not null default now());
alter table public.ui_assets add column if not exists transparent boolean not null default true, add column if not exists anchor text not null default 'center', add column if not exists asset_type text not null default 'image', add column if not exists mime_type text, add column if not exists is_animated boolean not null default false, add column if not exists animation_type text, add column if not exists duration_ms integer, add column if not exists loop boolean not null default true, add column if not exists metadata jsonb not null default '{}'::jsonb, add column if not exists position_x numeric not null default 0, add column if not exists position_y numeric not null default 0, add column if not exists width numeric, add column if not exists height numeric, add column if not exists z_index integer not null default 0;
alter table public.store_items add column if not exists asset_type text not null default 'image', add column if not exists mime_type text, add column if not exists is_animated boolean not null default false, add column if not exists animation_type text, add column if not exists duration_ms integer, add column if not exists loop boolean not null default true, add column if not exists metadata jsonb not null default '{}'::jsonb;
create table if not exists public.ui_components (id uuid primary key default gen_random_uuid(), component_key text not null unique, screen_key text not null, title_ar text not null, visible boolean not null default true, enabled boolean not null default true, position_x numeric not null default 0, position_y numeric not null default 0, width numeric, height numeric, z_index integer not null default 0, style jsonb not null default '{}'::jsonb, action jsonb not null default '{}'::jsonb, updated_at timestamptz not null default now());
insert into storage.buckets(id,name,public) values ('pharaoh-assets','pharaoh-assets',true) on conflict (id) do update set public=true;
-- RLS/policies and admin RPCs are defined in the Supabase migration history:
-- admin_asset_studio_and_storage, admin_agency_operations, admin_theme_config_policies.
