"use client";

import { useEffect, useState } from "react";\nimport type { CSSProperties } from "react";
import { useParams, useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";
import VoiceClient from "@/components/VoiceClient";

type Message={id:string;message:string;created_at:string;profiles?:{display_name:string}|null};
type Seat={seat_no:number;user_id:string|null;is_muted:boolean;locked:boolean;profiles?:{display_name:string;avatar_url:string|null}|null};\ntype Theme={app_name:string;primary_color:string;secondary_color:string;background_color:string;surface_color:string;text_color:string;muted_text_color:string;border_color:string;accent_color:string;radius:string;logo_url:string|null;background_image_url:string|null};\ntype Asset={area:string;asset_key:string;image_url:string|null;label:string|null;enabled:boolean};

export default function RoomPage(){
 const {id}=useParams<{id:string}>(); const router=useRouter();
 const [room,setRoom]=useState<any>(null); const [seats,setSeats]=useState<Seat[]>([]); const [theme,setTheme]=useState<Theme|null>(null); const [assets,setAssets]=useState<Record<string,Asset>>({});\n const icon=(key:string,emoji:string)=>{const a=assets["room:"+key];return a?.enabled&&a.image_url?<img src={a.image_url} alt={a.label||""}/>:emoji}; const [messages,setMessages]=useState<Message[]>([]); const [text,setText]=useState(""); const [userId,setUserId]=useState<string|null>(null); const [joined,setJoined]=useState(false); const [muted,setMuted]=useState(false);
 useEffect(()=>{load(); const ch=supabase.channel("room-"+id).on("postgres_changes",{event:"*",schema:"public",table:"room_messages",filter:"room_id=eq."+id},load).on("postgres_changes",{event:"*",schema:"public",table:"room_seats",filter:"room_id=eq."+id},load).subscribe(); return()=>{supabase.removeChannel(ch)}},[id]);
 async function load(){const [t,a]=await Promise.all([supabase.from("ui_theme").select("*").eq("id",1).maybeSingle(),supabase.from("ui_assets").select("*").eq("enabled",true).eq("area","room")]);if(t.data)setTheme(t.data as Theme);const map:Record<string,Asset>={};(a.data??[]).forEach((x:any)=>map["room:"+x.asset_key]=x);setAssets(map);const {data:{user}}=await supabase.auth.getUser();setUserId(user?.id??null);if(!user){setRoom(null);setSeats([]);setMessages([]);setJoined(false);setMuted(false);return}const [r,s,m]=await Promise.all([supabase.from("rooms").select("*").eq("id",id).single(),supabase.from("room_seats").select("*,profiles(display_name,avatar_url)").eq("room_id",id).order("seat_no"),supabase.from("room_messages").select("*,profiles(display_name)").eq("room_id",id).order("created_at",{ascending:true}).limit(100)]);setRoom(r.data);setSeats((s.data??[]) as Seat[]);setMessages((m.data??[]) as Message[]);const mine=((s.data??[]) as any[]).find(x=>x.user_id===user.id);setJoined(!!mine);setMuted(!!mine?.is_muted);}
 async function send(){if(!userId||!text.trim())return; await supabase.from("room_messages").insert({room_id:id,user_id:userId,message:text.trim()});setText("");}
 async function join(){const {error}=await supabase.rpc("join_room",{p_room_id:id,p_seat_no:null});if(error){alert(error.message);return}setJoined(true);load()}
 async function leave(){await supabase.rpc("leave_room",{p_room_id:id});setJoined(false);setMuted(false);load()} async function toggleMute(){if(!joined)return;const next=!muted;const {error}=await supabase.rpc("set_my_mute",{p_room_id:id,p_muted:next});if(error){alert(error.message);return}setMuted(next);load()}
 const themeStyle=theme?({["--primary" as any]:theme.primary_color,["--secondary" as any]:theme.secondary_color,["--bg" as any]:theme.background_color,["--surface" as any]:theme.surface_color,["--text" as any]:theme.text_color,["--muted" as any]:theme.muted_text_color,["--border" as any]:theme.border_color,["--accent" as any]:theme.accent_color,["--radius" as any]:theme.radius,backgroundImage:theme.background_image_url?`url(${theme.background_image_url})`:undefined} as CSSProperties):undefined;\n if(!room)return <main className="room" style={themeStyle}><button onClick={()=>router.back()}>← رجوع</button><div className="empty">جاري تحميل الغرفة...</div></main>;
 return <main className="room" style={themeStyle}><header><button className="icon" onClick={()=>router.back()}>{icon("back","←")}</button><div><b>{room.name}</b><span>{room.title||"غرفة صوتية"}</span></div><span className="live">● مباشر</span></header><VoiceClient roomId={id} userId={userId} enabled={joined} muted={muted}/><section className="room-body"><div className="seats">{seats.map(s=><div className={"seat "+(s.user_id?"filled":"")} key={s.seat_no}><div className="seat-avatar">{s.profiles?.avatar_url?<img src={s.profiles.avatar_url} alt=""/> :icon("mic","🎙️")}</div><small>{s.user_id?s.profiles?.display_name||"عضو":"مقعد "+s.seat_no}</small>{s.is_muted&&<i>🔇</i>}</div>)}</div><div className="chat-box">{messages.map(m=><div className="msg" key={m.id}><b>{m.profiles?.display_name||"مستخدم"}</b><span>{m.message}</span></div>)}</div></section><footer className="room-actions">{joined?<button onClick={leave}>{icon("leave","↩")} خروج</button>:<button onClick={join}>{icon("join","🎙️")} دخول المقعد</button>}<input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="اكتب رسالة..." /><button onClick={send}>{icon("send","➤")} إرسال</button><button>{icon("gift","🎁")}</button><button>{icon("mic","🎤")}</button></footer></main>;
}
